name: "LDS Feed Action"
description: "Get LINZ Data Service statistics for datasets updates"
author: "Daniel Silk"
inputs:
  layerid:
    description: "LINZ Data Service layer id"
    default: 52054
    required: true
  timeframe:
    description: "Check for update in the last x number of days, hours or minutes"
    default: 7
    required: true
  units:
    description: "Either 'days', 'hours' or 'minutes'"
    default: days
    required: true
outputs:
  updateFound:
    description: "Output from the action"
  datasetTitle:
    description: "The title of the dataset"
  revisionNumber:
    description: "The unique identifier for the dataset update"
  publishedTime:
    description: "Time that the update was published in the 'Pacific/Auckland' timezone"
  totalFeatures:
    description: "Total number of features in the layer after this update"
  adds:
    description: "Number of features added by the update"
  modifies:
    description: "Number of features modified by the update"
  deletes:
    description: "Number of features deleted by the update"

runs:
  using: "docker"
  image: "Dockerfile"
