name: "Python Container Action Template"
description: "Get started with Python Container actions"
author: "Daniel Silk"
inputs:
  layerid:
    description: "LINZ Data Service layer id"
    default: 101290
    required: true
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
