name: Lint & Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v1
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Pip Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: lint${{ matrix.python }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            lint${{ matrix.python }}-pip-:
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Commit Lint
        run: | 
          gitlint --commits origin/master..
      - name: Format
        run: |
          black . --check --diff
      - name: Doc Style
        run: |
          pydocstyle --convention=numpy .
      - name: Lint
        run: |
          pylint main.py
      - name: Import Sorting
        run: |
          isort -rc . --check --diff
      - name: Test
        run: |
          export INPUT_LAYERID=52054
          export INPUT_TIMEFRAME=10000
          export INPUT_UNITS=days
          pytest . --cov-report xml --cov=main
      - name: Coverage
        uses: codecov/codecov-action@797e928
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
